# Generated by Django 4.1 on 2023-11-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_text', models.CharField(max_length=120)),
                ('_decoded', models.CharField(max_length=120)),
            ],
        ),
    ]
