# Generated by Django 4.1 on 2023-11-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decoder', '0002_rename__decoded_usermessage_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='text',
            new_name='message',
        ),
    ]
