# Generated by Django 4.1 on 2023-11-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='_encoded',
            new_name='encoded',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='_text',
            new_name='text',
        ),
    ]
