# Generated by Django 4.1 on 2023-11-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0004_alter_usermessage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='text',
            field=models.CharField(max_length=120),
        ),
    ]
