# Generated by Django 4.1 on 2023-11-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0005_alter_usermessage_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='text',
            new_name='message',
        ),
    ]
